In [1]:
#introducao ao numpy

import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)
print("shape =")
print(a.shape)
print("linha = ")
print(a.shape[0])
print("coluna = ")
print(a.shape[1])
print("nome do tipo = ")
print(a.dtype.name)
print("tamanho do item = ")
print(a.itemsize)
print("size = ")
print(a.size)
print("tipo = ")
print(type(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
shape =
(3, 5)
linha = 
3
coluna = 
5
nome do tipo = 
int64
tamanho do item = 
8
size = 
15
tipo = 
<class 'numpy.ndarray'>


In [2]:
#Criando um array numpy
a = np.array([2,3,4])
print(a)
b = np.array([(1.5,2,3), (4,5,6)])
print(b)
c = np.array( [ [1,2], [3,4] ], dtype=complex )
print(c)
print(c.dtype)

[2 3 4]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
complex128


In [3]:
#criando matriz de zeros
x = np.zeros( (3,4) )
print(x)
#criando matriz de 1s
y = np.ones( (2,3,4), dtype=np.int16 )
print(y)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [4]:
#criando valores em sequencia (inteiros)
sequencia = np.arange( 10, 30, 3 )
print(sequencia)
sequencia1 = np.arange( 0, 2, 0.3 )
print(sequencia1)

[10 13 16 19 22 25 28]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [5]:
#criando valores em sequencia (float)
sequencia2 = np.linspace( 0, 2, 9 )
print(sequencia2)
#criando numeros aleatorios
aleatorio = np.random.rand(3,2)
print(aleatorio)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[[0.87870411 0.71011745]
 [0.0446047  0.0218423 ]
 [0.51594766 0.76570361]]


In [6]:
#mudando o formato do array
a = np.arange(6)                         # 1d array
print('1D array')
print(a)
b = np.arange(12).reshape(4,3)           # 2d array
print('2D array')
print(b)
c = np.arange(24).reshape(2,3,4)         # 3d array
print('3D array')
print(c)

1D array
[0 1 2 3 4 5]
2D array
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
3D array
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [8]:
#forca impressao do array completo
np.set_printoptions(threshold=np.nan)
print(np.arange(100))
print(np.arange(100).reshape(10,10))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [9]:
#operacoes basicas
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print(a)
print(b)
c = a - b
print(c)
f = b**2
g = 10*np.sin(a)

if np.mean(f) > np.mean(g):
    print('f > g')
    print(f)
else:
    print('f < g')
    print(g)

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]
f > g
[0 1 4 9]


In [10]:
A = np.array( [[1,1],
            [0,1]] )
B = np.array( [[2,0],
            [3,4]] )

print('A * B = ')
print(A * B)
print('A @ B = ')
print(A @ B)
print('A.dot(B)')
print(A.dot(B))

A * B = 
[[2 0]
 [0 4]]
A @ B = 
[[5 4]
 [3 4]]
A.dot(B)
[[5 4]
 [3 4]]


In [11]:
a = np.ones((2,3), dtype=int)
print(a)
b = np.random.random((2,3))
print(b)
a *= 3
print(a)
b += a
print(b)
a += b.astype('int64') #retire o cast! Veja o que acontece.
print(a)

[[1 1 1]
 [1 1 1]]
[[0.42994929 0.29922317 0.31901957]
 [0.7413765  0.35117722 0.40661335]]
[[3 3 3]
 [3 3 3]]
[[3.42994929 3.29922317 3.31901957]
 [3.7413765  3.35117722 3.40661335]]
[[6 6 6]
 [6 6 6]]


In [12]:
a = np.random.random((2,3))
print(a)
print(a.sum())
print(a.min())
print(a.max())

[[0.73971738 0.36976931 0.87493726]
 [0.27083385 0.24596224 0.45129984]]
2.952519863702667
0.2459622367452865
0.8749372591937938


In [13]:
b = np.arange(12).reshape(3,4)
print(b)
print(b.sum(axis=0) )
print(b.min(axis=1))
print(b.cumsum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [16]:
#Indexing, Slicing and Iterating¶

a = np.arange(10)**3
print(a)
print(a[2])
print(a[2:5])
a[:6:2] = -1000
print(a)
print(a[::-1])


[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[-1000     1 -1000    27 -1000   125   216   343   512   729]
[  729   512   343   216   125 -1000    27 -1000     1 -1000]


In [20]:
for i in a:
    print(i**(2))


1000000
1
1000000
729
1000000
15625
46656
117649
262144
531441


array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])